POST  http://localhost:3333/transactions/

Content-Type: application/json

{
  "value": 100,
  "name": "Teste",
  "category": "Linguiça",
  "description": "Teste de inserção de dados",
  "type": "entrada"
}