
GET  http://localhost:3333/transactions

### Create a new transaction
POST http://localhost:3333/transactions/
Content-Type: application/json

{
  "value": 1500,
  "name": "Outlier",
  "category": "salario",
  "description": "pagamento das tasks",
  "type": "entrada"
}